services:
  mod:
    build: .
    container_name: mod
    command: python src/mod_emulator.py conf/conf_mod.yaml
    volumes:
      - ./src:/app/src
      - ./conf:/app/conf
    cap_add:
      - NET_RAW
      - NET_ADMIN
    tty: true
    stdin_open: true
    networks:
      - substation

  rza1:
    build: .
    container_name: rza1
    command: python src/rza_emulator.py conf/conf_rza1.yaml
    volumes:
      - ./src:/app/src
      - ./conf:/app/conf
    cap_add:
      - NET_RAW
      - NET_ADMIN
    tty: true
    stdin_open: true
    networks:
      - substation
  rza2:
    build: .
    container_name: rza2
    command: python src/rza_emulator.py conf/conf_rza2.yaml
    volumes:
      - ./src:/app/src
      - ./conf:/app/conf
    cap_add:
      - NET_RAW
      - NET_ADMIN
    tty: true
    stdin_open: true
    networks:
      - substation
  rza3:
    build: .
    container_name: rza3
    command: python src/rza_emulator.py conf/conf_rza3.yaml
    volumes:
      - ./src:/app/src
      - ./conf:/app/conf
    cap_add:
      - NET_RAW
      - NET_ADMIN
    tty: true
    stdin_open: true
    networks:
      - substation
  

networks:
  substation: